### ISSUE TITLE
Unable to install to Joomla

### ISSUE THREAD

**Issue by revenger73** [fidmor89/AppInsights-Joomla#3]
I have downloaded the zip, unzipped, and use option in Joomla to Install package from directory.

I get an error "Can't find install package"

I did the same steps from video https://www.youtube.com/watch?v=iq3oAy_IFEk&feature=youtu.be

Kind regards,

Remko

**Comment by fidmor89** [comment]
Thanks for reporting.  Its been a while since we last updated this repository it should be working just fine.  I'll be testing it ASAP. Try downloading from http://appinsightspluginsphp.azurewebsites.net/ while this issue is fixed.

**Comment by revenger73** [comment]
Thanks for the link....but that one is not working either (upload as zip, or
upload from directory):

Warning
JInstaller: :Installeren: File does not exists
/storage/web/public/sites/www.nipponinu.nl/tmp/install_558cfb739b171/AppInsightsPlugin/appinsightsplugin.php

Plugin install: Kan bestanden niet kopiëren van de bron.

Error
Error installing plugin

We are using latest stable Joomla 3.4.1 (dutch version NL-nl). 

Am I missing any step?

Kind Regards,

Remko

**Comment by revenger73** [comment]
Hmmm...strange...installed WebMatrix 3, created a new Joomla website (not NL-nl), installed plugin...installation ok.

**Comment by fidmor89** [comment]
The language shouldn't be a problem neither the web matrix.

We were unable to replicate your issue. It must be a specific configuration with your site. Since you have already successfully installed it i'm closing this issue but please do keep in touch if it happens again and you have more information about it.

**Comment by revenger73** [comment]
Managed to install in to production by changing the casing of the file AppInsightsPlugin.php in appinsightsplugin.xml (was all in lowercase instead of camelcase). The test website was on Azure, the production website is with a different hosting party (file system differences with case-sensitive issue i guess).

Then plugin install succesfully (and can provide instrumentation key). But the javascript code is NOT inserted in the pages. 

No AppInsight Javascript on http://www.nipponinu.nl/
AppInsight Javascript on: http://appinsightsjoomla.azurewebsites.net/

We are using a RocketTheme template RT_Radiance.
